---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mariadb
    release: ghost
  name: ghost-mariadb-tests
  namespace: ghost
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h ghost-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }

