---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ghost
    release: ghost
  name: ghost
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
