---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mariadb
    release: ghost
  name: ghost-mariadb
  namespace: ghost
type: Opaque
data:
  mariadb-password: "my secret password"
  mariadb-root-password: "my secret password"